"""
04_channel_charting.py — Unsupervised channel chart generation.

Applies dimensionality reduction to the CSI fingerprint matrix to produce a
2-D channel chart *without* using position labels.  Which methods are run is
controlled by the scene's ``features_config.json`` (section
``channel_charting``):

  • pca         — Principal Component Analysis (linear, fast baseline)
  • tsne        — t-distributed Stochastic Neighbour Embedding
  • autoencoder — Unsupervised autoencoder with a 2-D latent space
  • umap        — Uniform Manifold Approximation and Projection

Quality metrics: Trustworthiness (TW), Continuity (CT), Kruskal Stress (KS),
and Nearest-Neighbour Localisation Error (NNLE).

Requires: <SCENE_DIR>/fingerprint_rt_dataset.h5
(generated by 01_generate_dataset or 03_localization).

Usage
-----
    python 04_channel_charting.py [scene_name] [results_dir]

    scene_name   — name of the scene folder (default: "Otaniemi_small")
    results_dir  — optional override for the output directory

Change the scene_name argument in main() to switch between scenes.
"""

import warnings
import sys
import importlib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

warnings.filterwarnings('ignore')


# ── Config ────────────────────────────────────────────────────────────────────

def setup_config(scene_name="Otaniemi_small"):
    """Load scene config and resolve the scene output directory.

    Parameters
    ----------
    scene_name : str
        Name of the scene folder (must contain ``scene_config.json``).

    Returns
    -------
    cfg : dict
        Scene configuration dict from :func:`config.get_scene_config`.
    SCENE_DIR : Path
        Absolute path to the scene output directory (created if absent).
    """
    from config import get_scene_config, scene_dir

    cfg = get_scene_config(scene_name)
    SCENE_DIR = scene_dir(cfg)
    print(f"Scene : {cfg['SCENE_XML_FILE_NAME']}")
    print(f"Data  : {SCENE_DIR}")
    return cfg, SCENE_DIR


def setup_pictures_dir(SCENE_DIR):
    """Create and return the picture output directory for this script.

    Parameters
    ----------
    SCENE_DIR : Path
        Root output directory for the scene.

    Returns
    -------
    Path
        ``<SCENE_DIR>/pictures/04_channel_charting/``, created if absent.
    """
    PICTURES_DIR = SCENE_DIR / "pictures" / "04_channel_charting"
    PICTURES_DIR.mkdir(parents=True, exist_ok=True)
    return PICTURES_DIR


# ── Load and scale fingerprint dataset ───────────────────────────────────────

def load_and_scale_fingerprints(SCENE_DIR):
    """Load the fingerprint HDF5 cache and apply standard scaling.

    Parameters
    ----------
    SCENE_DIR : Path
        Scene directory containing ``fingerprint_rt_dataset.h5``.

    Returns
    -------
    X_cc_scaled : (N, D) ndarray
        Standardised feature matrix (zero-mean, unit-variance per feature).
    pos_cc : (N, 2) ndarray
        Corresponding [x, y] UE positions.
    N : int
        Total number of samples.
    """
    from sklearn.preprocessing import StandardScaler
    from features import load_fingerprint_dataset

    csi_fingerprints, fingerprint_positions = load_fingerprint_dataset(SCENE_DIR)
    print(f"Fingerprints: {csi_fingerprints.shape}")

    X_cc   = csi_fingerprints.copy()
    pos_cc = fingerprint_positions.copy()

    scaler_cc   = StandardScaler()
    X_cc_scaled = scaler_cc.fit_transform(X_cc)
    N = X_cc_scaled.shape[0]
    print(f"Dataset ready: N={N} samples, {X_cc_scaled.shape[1]} features")
    return X_cc_scaled, pos_cc, N


# ── Dimensionality reduction methods ─────────────────────────────────────────

def run_pca_charting(X_cc_scaled):
    """Compute a PCA channel chart and print quality metrics.

    Parameters
    ----------
    X_cc_scaled : (N, D) ndarray
        Standardised fingerprint feature matrix.

    Returns
    -------
    pca_res : dict
        Result dict with keys: ``Z`` (2-D embedding), ``tw``, ``ct``, ``ks``,
        ``explained_var``, ``X_pca50`` (50-component PCA used as input to
        t-SNE and UMAP for speed).
    Z_pca : (N, 2) ndarray
        The 2-D PCA embedding.
    """
    from channel_charting import run_pca

    pca_res = run_pca(X_cc_scaled)
    Z_pca   = pca_res['Z']
    print(f"PCA: TW={pca_res['tw']:.4f}  CT={pca_res['ct']:.4f}  KS={pca_res['ks']:.4f}")
    return pca_res, Z_pca


def run_tsne_charting(X_cc_scaled, X_pca50, pos_cc):
    """Compute a t-SNE channel chart, sweeping perplexity, and print metrics.

    Parameters
    ----------
    X_cc_scaled : (N, D) ndarray
        Standardised feature matrix.
    X_pca50 : (N, 50) ndarray
        50-component PCA pre-projection (used as t-SNE input for speed).
    pos_cc : (N, 2) ndarray
        True [x, y] positions (used to compute NNLE).

    Returns
    -------
    tsne_res : dict
        Result dict with keys: ``Z``, ``tw``, ``ct``, ``ks``, ``nnle``,
        ``best_perp``.
    Z_tsne : (N, 2) ndarray
        The best t-SNE 2-D embedding.
    """
    from channel_charting import run_tsne

    tsne_res = run_tsne(X_cc_scaled, X_pca50=X_pca50, pos_true=pos_cc)
    Z_tsne   = tsne_res['Z']
    nnle_str = f"  NNLE={tsne_res['nnle']:.2f} m" if not np.isnan(tsne_res['nnle']) else ""
    print(f"t-SNE (best perp={tsne_res['best_perp']}): "
          f"TW={tsne_res['tw']:.4f}  CT={tsne_res['ct']:.4f}  KS={tsne_res['ks']:.4f}{nnle_str}")
    return tsne_res, Z_tsne


def run_autoencoder_charting(X_cc_scaled, pos_cc):
    """Train an unsupervised autoencoder and compute channel chart metrics.

    Parameters
    ----------
    X_cc_scaled : (N, D) ndarray
        Standardised feature matrix.
    pos_cc : (N, 2) ndarray
        True [x, y] positions (used to compute NNLE).

    Returns
    -------
    ae_res : dict
        Result dict with keys: ``Z``, ``tw``, ``ct``, ``ks``, ``nnle``.
    Z_ae : (N, 2) ndarray
        The 2-D autoencoder latent-space embedding.
    """
    from channel_charting import run_autoencoder

    ae_res = run_autoencoder(X_cc_scaled, pos_true=pos_cc)
    Z_ae   = ae_res['Z']
    nnle_str = f"  NNLE={ae_res['nnle']:.2f} m" if not np.isnan(ae_res['nnle']) else ""
    print(f"AE: TW={ae_res['tw']:.4f}  CT={ae_res['ct']:.4f}  KS={ae_res['ks']:.4f}{nnle_str}")
    return ae_res, Z_ae


def run_umap_charting(X_cc_scaled, X_pca50, pos_cc):
    """Compute a UMAP channel chart if ``umap-learn`` is installed.

    Parameters
    ----------
    X_cc_scaled : (N, D) ndarray
        Standardised feature matrix.
    X_pca50 : (N, 50) ndarray
        50-component PCA pre-projection (used as UMAP input for speed).
    pos_cc : (N, 2) ndarray
        True [x, y] positions (used to compute NNLE).

    Returns
    -------
    umap_res : dict
        Result dict with keys: ``Z``, ``tw``, ``ct``, ``ks``, ``nnle``,
        ``best_n``.  Empty dict if ``umap-learn`` is not installed.
    Z_umap : (N, 2) ndarray or None
        The 2-D UMAP embedding, or ``None`` if UMAP is unavailable.
    UMAP_OK : bool
        ``True`` when UMAP ran successfully.
    """
    try:
        from channel_charting import run_umap

        umap_res = run_umap(X_cc_scaled, X_pca50=X_pca50, pos_true=pos_cc)
        Z_umap   = umap_res['Z']
        UMAP_OK  = True
        nnle_str = f"  NNLE={umap_res['nnle']:.2f} m" if not np.isnan(umap_res['nnle']) else ""
        print(f"UMAP (best n={umap_res['best_n']}): "
              f"TW={umap_res['tw']:.4f}  CT={umap_res['ct']:.4f}  KS={umap_res['ks']:.4f}{nnle_str}")
    except ImportError:
        print("umap-learn not installed — install with: pip install umap-learn")
        umap_res = {}
        Z_umap   = None
        UMAP_OK  = False
    return umap_res, Z_umap, UMAP_OK


# ── Visualise channel charts ──────────────────────────────────────────────────

def visualise_channel_charts(embeddings, titles,
                              pos_cc, cfg, PICTURES_DIR):
    """Save channel chart figures coloured by physical X, Y, and distance.

    Produces three figures:
    * ``channel_charts_coloured_x.png`` — coloured by X coordinate
    * ``channel_charts_coloured_y.png`` — coloured by Y coordinate
    * ``channel_charts_comparison.png`` — coloured by distance from scene centre

    Smooth, monotone gradients confirm the chart preserves spatial order.

    Parameters
    ----------
    embeddings : list of (N, 2) ndarray
        2-D embeddings for each enabled method.
    titles : list of str
        Per-method subplot titles (include metric values).
    pos_cc : (N, 2) ndarray
        True [x, y] UE positions.
    cfg : dict
        Scene configuration — requires ``SCENE_CX`` and ``SCENE_CY``.
    PICTURES_DIR : Path
        Output directory for the figures.
    """
    n_charts = len(embeddings)

    for axis_idx, (axis_label, cmap, fname) in enumerate([
        ('X (m)', 'viridis',  'channel_charts_coloured_x.png'),
        ('Y (m)', 'plasma',   'channel_charts_coloured_y.png'),
    ]):
        color_vals = pos_cc[:, axis_idx]
        fig, axes = plt.subplots(1, n_charts, figsize=(6 * n_charts, 5))
        if n_charts == 1:
            axes = [axes]
        for ax, Z, title in zip(axes, embeddings, titles):
            sc = ax.scatter(Z[:, 0], Z[:, 1], c=color_vals, cmap=cmap,
                            s=18, alpha=0.8)
            plt.colorbar(sc, ax=ax, label=axis_label)
            ax.set_title(title, fontsize=9, fontweight='bold')
            ax.set_xlabel('Dim 1'); ax.set_ylabel('Dim 2')
            ax.grid(True, alpha=0.2)
        plt.suptitle(f'Channel Charts — coloured by physical {axis_label}',
                     fontsize=12, fontweight='bold', y=1.01)
        plt.tight_layout()
        plt.savefig(PICTURES_DIR / fname, dpi=150, bbox_inches='tight')
        plt.close()

    # Distance-from-centre figure (summary / report overview)
    scene_center  = np.array([cfg['SCENE_CX'], cfg['SCENE_CY']])
    color_by_dist = np.linalg.norm(pos_cc - scene_center, axis=1)
    fig, axes = plt.subplots(1, n_charts, figsize=(6 * n_charts, 5))
    if n_charts == 1:
        axes = [axes]
    for ax, Z, title in zip(axes, embeddings, titles):
        sc = ax.scatter(Z[:, 0], Z[:, 1], c=color_by_dist, cmap='plasma',
                        s=18, alpha=0.8)
        plt.colorbar(sc, ax=ax, label='Dist from centre (m)')
        ax.set_title(title, fontsize=9, fontweight='bold')
        ax.set_xlabel('Dim 1'); ax.set_ylabel('Dim 2')
        ax.grid(True, alpha=0.2)
    plt.suptitle('Channel Charts — coloured by distance from scene centre',
                 fontsize=12, fontweight='bold', y=1.01)
    plt.tight_layout()
    plt.savefig(PICTURES_DIR / 'channel_charts_comparison.png', dpi=150,
                bbox_inches='tight')
    plt.close()


# ── PCA explained variance ────────────────────────────────────────────────────

def plot_pca_variance(pca_res, PICTURES_DIR):
    """Save a cumulative explained-variance plot for PCA.

    Horizontal reference lines are drawn at 90 % and 95 % to indicate how
    many components are needed to explain most of the variance.

    Parameters
    ----------
    pca_res : dict
        PCA result dict containing ``explained_var`` (cumulative variance
        array from :func:`channel_charting.run_pca`).
    PICTURES_DIR : Path
        Output directory for ``pca_explained_variance.png``.
    """
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(np.arange(1, len(pca_res['explained_var']) + 1),
            pca_res['explained_var'] * 100, 'o-', lw=2)
    ax.axhline(90, color='red',    ls='--', label='90%')
    ax.axhline(95, color='orange', ls='--', label='95%')
    ax.set_xlabel('Number of Components'); ax.set_ylabel('Cumulative Variance (%)')
    ax.set_title('PCA Explained Variance'); ax.legend(); ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(PICTURES_DIR / 'pca_explained_variance.png', dpi=150)
    # plt.show()


# ── Summary table ─────────────────────────────────────────────────────────────

def build_summary_table(cc_results_list, SCENE_DIR):
    """Print a metrics table and save it to CSV.

    Parameters
    ----------
    cc_results_list : list of (str, dict)
        Sequence of ``(method_name, result_dict)`` pairs for each enabled
        charting method.  Result dicts must contain ``tw``, ``ct``, ``ks``,
        and optionally ``nnle`` and ``best_perp`` / ``best_n``.
    SCENE_DIR : Path
        Directory where ``channel_charting_metrics.csv`` is saved.

    Returns
    -------
    cc_methods : list of str
    tw_vals, ct_vals, ks_vals, nnle_vals : list of float
    """
    cc_methods = [r[0] for r in cc_results_list]
    tw_vals    = [r[1]['tw']  for r in cc_results_list]
    ct_vals    = [r[1]['ct']  for r in cc_results_list]
    ks_vals    = [r[1]['ks']  for r in cc_results_list]
    nnle_vals  = [r[1].get('nnle', float('nan')) for r in cc_results_list]

    df_cc = pd.DataFrame({
        'Method':               cc_methods,
        'TW (↑ better)':       [f'{v:.4f}' for v in tw_vals],
        'CT (↑ better)':       [f'{v:.4f}' for v in ct_vals],
        'KS (↓ better)':       [f'{v:.4f}' for v in ks_vals],
        'NNLE m (↓ better)':   [f'{v:.2f}' if not np.isnan(v) else 'n/a' for v in nnle_vals],
    })
    print("\n" + "=" * 70)
    print("CHANNEL CHARTING SUMMARY")
    print("=" * 70)
    print(df_cc.to_string(index=False))

    csv_out = SCENE_DIR / 'channel_charting_metrics.csv'
    df_cc.to_csv(csv_out, index=False)
    print(f"\nSaved → {csv_out}")
    return cc_methods, tw_vals, ct_vals, ks_vals, nnle_vals


# ── Automated metric interpretation ──────────────────────────────────────────

def print_metric_winners(cc_methods, tw_vals, ct_vals, ks_vals, nnle_vals=None):
    """Print per-metric winner and a qualitative verdict for every method.

    Parameters
    ----------
    cc_methods : list of str
        Method names in the same order as the value lists.
    tw_vals, ct_vals, ks_vals : list of float
        Trustworthiness, Continuity, and Kruskal Stress values.
    nnle_vals : list of float or None
        Nearest-Neighbour Localisation Errors (NaN for methods without NNLE).
    """
    tw_arr = np.array(tw_vals, dtype=float)
    ct_arr = np.array(ct_vals, dtype=float)
    ks_arr = np.array(ks_vals, dtype=float)

    best_tw  = cc_methods[int(np.argmax(tw_arr))]
    best_ct  = cc_methods[int(np.argmax(ct_arr))]
    best_ks  = cc_methods[int(np.argmin(ks_arr))]

    def _norm01(v):
        return (v - v.min()) / ((v.max() - v.min()) + 1e-12)

    combined     = (_norm01(tw_arr) + _norm01(ct_arr) + (1 - _norm01(ks_arr))) / 3
    best_overall = cc_methods[int(np.argmax(combined))]

    nnle_arr = np.array(nnle_vals if nnle_vals is not None else [float('nan')] * len(cc_methods))
    valid_nnle = ~np.isnan(nnle_arr)
    best_nnle = cc_methods[int(np.nanargmin(nnle_arr))] if valid_nnle.any() else 'n/a'

    print("─" * 60)
    print("METRIC WINNERS")
    print("─" * 60)
    print(f"  Best Trustworthiness (TW ↑)  : {best_tw}")
    print(f"  Best Continuity       (CT ↑)  : {best_ct}")
    print(f"  Best KS distance      (KS ↓)  : {best_ks}")
    print(f"  Best NNLE             (↓ m)   : {best_nnle}")
    print(f"  Best overall avg rank         : {best_overall}")
    print("─" * 60)
    print(f"\nTW range : {tw_arr.min():.4f} – {tw_arr.max():.4f}  (1.0 = ideal)")
    print(f"CT range : {ct_arr.min():.4f} – {ct_arr.max():.4f}  (1.0 = ideal)")
    print(f"KS range : {ks_arr.min():.4f} – {ks_arr.max():.4f}  (0.0 = ideal)")
    if valid_nnle.any():
        print(f"NNLE range : {np.nanmin(nnle_arr):.2f} – {np.nanmax(nnle_arr):.2f} m  (0 = ideal)")

    for i, (name, tw, ct, ks, _) in enumerate(zip(cc_methods, tw_arr, ct_arr, ks_arr, combined)):
        flag = " ← best overall" if name == best_overall else ""
        print(f"\n  {name}{flag}")
        verdict_tw = "good" if tw > 0.9 else ("ok" if tw > 0.8 else "poor")
        verdict_ct = "good" if ct > 0.9 else ("ok" if ct > 0.8 else "poor")
        verdict_ks = "good" if ks < 0.1 else ("ok" if ks < 0.2 else "poor")
        nnle_str = ""
        if nnle_vals is not None and not np.isnan(nnle_arr[i]):
            nnle_str = f"  NNLE={nnle_arr[i]:.2f} m"
        print(f"    TW={tw:.4f} ({verdict_tw})  CT={ct:.4f} ({verdict_ct})  KS={ks:.4f} ({verdict_ks}){nnle_str}")


# ── Save channel charting cache ───────────────────────────────────────────────

def save_cc_cache_results(cc_results_list, pos_cc, N, SCENE_DIR):
    """Serialise all channel chart embeddings and metrics to HDF5.

    Parameters
    ----------
    cc_results_list : list of (str, dict)
        Sequence of ``(method_name, result_dict)`` pairs.
    pos_cc : (N, 2) ndarray
        True [x, y] UE positions.
    N : int
        Number of samples.
    SCENE_DIR : Path
        Directory where ``channel_charting_dataset.h5`` is saved.
    """
    from channel_charting import save_cc_cache

    cc_results = {
        name: dict(Z=res['Z'], tw=res['tw'], ct=res['ct'], ks=res['ks'],
                   nnle=res.get('nnle', float('nan')))
        for name, res in cc_results_list
    }

    cache_path = str(SCENE_DIR / 'channel_charting_dataset.h5')
    save_cc_cache(cache_path, cc_results, pos_cc, extra_attrs={'n_samples': N})
    print(f"Saved channel charting cache → {cache_path}")


# ── Save Markdown report ──────────────────────────────────────────────────────

def save_report(SCENE_DIR, PICTURES_DIR):
    """Convert the accumulated Markdown report to a .md file.

    Parameters
    ----------
    SCENE_DIR : Path
        Scene output directory.
    PICTURES_DIR : Path
        Directory containing the generated plot images.
    """
    import report_utils
    importlib.reload(report_utils)
    from report_utils import save_notebook_report

    save_notebook_report(
        Path.cwd() / "04_channel_charting.ipynb",
        SCENE_DIR,
        pics_dir=PICTURES_DIR,
    )


# ── Main ──────────────────────────────────────────────────────────────────────

def main(scene_name="Otaniemi_small", results_dir=None):
    """Run the full channel charting pipeline for *scene_name*.

    Steps:
    1. Load scene config and feature config.
    2. Load and standardise the CSI fingerprint dataset.
    3. Run each enabled dimensionality-reduction method.
    4. Visualise the channel charts (coloured by X, Y, and distance).
    5. Print quality metrics and identify the best method.
    6. Save embeddings to HDF5 and metrics to CSV.
    7. Save a Markdown report.

    Which methods run is controlled by the ``channel_charting`` section of
    ``<scene_name>/features_config.json``.

    Parameters
    ----------
    scene_name : str
        Scene folder name (must contain ``scene_config.json`` and
        ``features_config.json``).
    results_dir : str or None
        Override for the output directory.  When ``None``, outputs are
        written to ``<SCENE_DIR>/``.
    """
    from config import get_features_config

    cfg, SCENE_DIR = setup_config(scene_name)
    feat_cfg = get_features_config(scene_name)
    cc_cfg   = feat_cfg["channel_charting"]

    OUTPUT_DIR = Path(results_dir) if results_dir is not None else SCENE_DIR
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    if results_dir is not None:
        PICTURES_DIR = OUTPUT_DIR / "pictures" / "04_channel_charting"
        PICTURES_DIR.mkdir(parents=True, exist_ok=True)
    else:
        PICTURES_DIR = setup_pictures_dir(SCENE_DIR)

    from report_utils import MarkdownReport
    report = MarkdownReport()
    report.add(f"""\
# 04 — Channel Charting

Applies dimensionality reduction to the CSI fingerprint matrix to produce a
2-D **channel chart** without using position labels.

Enabled methods (see ``features_config.json``):
{chr(10).join("- **" + m.upper() + "**" for m, en in cc_cfg.items() if en)}

Quality metrics: Trustworthiness (TW), Continuity (CT), Kruskal Stress (KS).

**Scene:** `{cfg['SCENE_XML_FILE_NAME']}`
**Data:** `{OUTPUT_DIR}`

**Requires:** `fingerprint_rt_dataset.h5` in the data directory
(generated by `01_generate_dataset.py` or `03_localization.py`).""")

    with report.capture():
        # Fingerprint cache belongs to the scene, not to the run output dir.
        X_cc_scaled, pos_cc, N = load_and_scale_fingerprints(SCENE_DIR)

    # ── Run enabled charting methods ──────────────────────────────────────────
    cc_results_list = []   # [(method_name, result_dict), ...]
    embeddings      = []
    titles          = []
    X_pca50         = None  # reused by t-SNE and UMAP

    if cc_cfg.get("pca", True):
        with report.capture():
            pca_res, Z_pca = run_pca_charting(X_cc_scaled)
        X_pca50 = pca_res.get('X_pca50')
        cc_results_list.append(("PCA", pca_res))
        embeddings.append(Z_pca)
        titles.append(
            f"PCA\nTW={pca_res['tw']:.3f}  CT={pca_res['ct']:.3f}  KS={pca_res['ks']:.3f}"
        )
    else:
        print("PCA disabled — skipping.")

    if cc_cfg.get("tsne", True):
        # t-SNE benefits from a PCA pre-projection; compute on the fly if PCA
        # was disabled.
        if X_pca50 is None:
            from sklearn.decomposition import PCA as _PCA
            X_pca50 = _PCA(n_components=min(50, X_cc_scaled.shape[1])).fit_transform(X_cc_scaled)
        with report.capture():
            tsne_res, Z_tsne = run_tsne_charting(X_cc_scaled, X_pca50, pos_cc)
        cc_results_list.append((f"t-SNE (perp={tsne_res['best_perp']})", tsne_res))
        embeddings.append(Z_tsne)
        nnle_s = f"  NNLE={tsne_res.get('nnle', float('nan')):.1f} m"
        titles.append(
            f"t-SNE (perp={tsne_res['best_perp']})\n"
            f"TW={tsne_res['tw']:.3f}  CT={tsne_res['ct']:.3f}  "
            f"KS={tsne_res['ks']:.3f}{nnle_s}"
        )
    else:
        print("t-SNE disabled — skipping.")

    if cc_cfg.get("autoencoder", True):
        with report.capture():
            ae_res, Z_ae = run_autoencoder_charting(X_cc_scaled, pos_cc)
        cc_results_list.append(("Autoencoder", ae_res))
        embeddings.append(Z_ae)
        nnle_s = f"  NNLE={ae_res.get('nnle', float('nan')):.1f} m"
        titles.append(
            f"Autoencoder\nTW={ae_res['tw']:.3f}  CT={ae_res['ct']:.3f}  "
            f"KS={ae_res['ks']:.3f}{nnle_s}"
        )
    else:
        print("Autoencoder disabled — skipping.")

    if cc_cfg.get("umap", True):
        if X_pca50 is None:
            from sklearn.decomposition import PCA as _PCA
            X_pca50 = _PCA(n_components=min(50, X_cc_scaled.shape[1])).fit_transform(X_cc_scaled)
        with report.capture():
            umap_res, Z_umap, UMAP_OK = run_umap_charting(X_cc_scaled, X_pca50, pos_cc)
        if UMAP_OK:
            cc_results_list.append((f"UMAP (n={umap_res['best_n']})", umap_res))
            embeddings.append(Z_umap)
            nnle_s = f"  NNLE={umap_res.get('nnle', float('nan')):.1f} m"
            titles.append(
                f"UMAP (n={umap_res['best_n']})\n"
                f"TW={umap_res['tw']:.3f}  CT={umap_res['ct']:.3f}  "
                f"KS={umap_res['ks']:.3f}{nnle_s}"
            )
    else:
        print("UMAP disabled — skipping.")

    if not cc_results_list:
        print("No channel charting methods are enabled. Edit features_config.json.")
        return

    # ── Visualise + summarise ─────────────────────────────────────────────────
    report.add("### Channel Charts — coloured by physical X coordinate")
    with report.capture():
        visualise_channel_charts(embeddings, titles, pos_cc, cfg, PICTURES_DIR)
    report.figure(PICTURES_DIR / 'channel_charts_coloured_x.png', OUTPUT_DIR)
    report.add("### Channel Charts — coloured by physical Y coordinate")
    report.figure(PICTURES_DIR / 'channel_charts_coloured_y.png', OUTPUT_DIR)
    report.add("### Channel Charts — coloured by distance from scene centre")
    report.figure(PICTURES_DIR / 'channel_charts_comparison.png', OUTPUT_DIR)

    if any(n == "PCA" for n, _ in cc_results_list):
        pca_result = next(r for n, r in cc_results_list if n == "PCA")
        report.add("### PCA Explained Variance")
        with report.capture():
            plot_pca_variance(pca_result, PICTURES_DIR)
        report.figure(PICTURES_DIR / 'pca_explained_variance.png', OUTPUT_DIR)

    with report.capture():
        cc_methods, tw_vals, ct_vals, ks_vals, nnle_vals = build_summary_table(
            cc_results_list, OUTPUT_DIR
        )
        print_metric_winners(cc_methods, tw_vals, ct_vals, ks_vals, nnle_vals)

    with report.capture():
        save_cc_cache_results(cc_results_list, pos_cc, N, OUTPUT_DIR)

    report.add("""\
## Analysis — What the Metrics Mean and How to Improve

### Metrics at a Glance

| Metric | Range | Direction | What it measures |
|--------|-------|-----------|-----------------|
| **TW** (Trustworthiness) | 0 → 1 | ↑ higher is better | Do close neighbours in the 2-D chart stay close in the real RF space? Punishes *false neighbours* that appear close in the chart but are far apart in reality. |
| **CT** (Continuity) | 0 → 1 | ↑ higher is better | Do close neighbours in real RF space stay close in the chart? Punishes *tears* where nearby UE locations end up far apart in the chart. |
| **KS** (Kolmogorov–Smirnov distance) | 0 → 1 | ↓ lower is better | Does the chart's pairwise-distance distribution match the true geographic one? Near 0 = geometrically faithful map; near 1 = global scale heavily distorted. |

A **good channel chart** should have TW ≈ CT ≈ 1 and KS ≈ 0.

---

### Practical Interpretation

- **TW ≈ CT > 0.9** — the chart is usable as a radio-fingerprint map: nearby chart
  points correspond to nearby real locations.  Values below ~0.8 mean only the
  topology is preserved, not the metric.
- **KS close to 0** — the chart preserves absolute distances well enough for
  ranging-based localisation or handover triggering.
- **TW > CT** — more false neighbours than tears (typical of t-SNE / UMAP at
  high perplexity).
- **CT > TW** — the chart folds/tears the space; common with aggressive reduction
  on sparse datasets.
- **All metrics moderate** — the CSI fingerprint does not contain enough geometric
  information; adding more BSs or angular features will help most.

---

### How to Improve the Metrics

| Problem | Likely cause | Action |
|---------|-------------|--------|
| Low TW | Too many false neighbours | Reduce t-SNE perplexity or UMAP `n_neighbors`; add AE regularisation |
| Low CT | Chart tears / folds | Add a continuity-penalising loss; try triplet-loss or siamese AE |
| High KS | Global scale distorted | Add Sammon-mapping or distance-preserving loss; use more subcarriers / BSs |
| All metrics mediocre | Too few BSs / features | Stack CSI from all BSs; include AoA/AoD features |
| AE overfits small dataset | Few UE positions | Enlarge grid in `config.py` (reduce `GRID_SPACING`) or add dropout |

The single fastest practical improvement is to **use all base stations** in the
fingerprint vector and to **replace plain MSE reconstruction with a contrastive /
triplet-loss autoencoder** so the latent space is explicitly trained to be
geometrically consistent.""")

    report.save(OUTPUT_DIR / '04_channel_charting_report.md')


if __name__ == "__main__":
    _scene = sys.argv[1] if len(sys.argv) > 1 else "Otaniemi_small"
    _results_dir = sys.argv[2] if len(sys.argv) > 2 else None
    main(_scene, _results_dir)
