#!/usr/bin/env python3
"""
write_features_config.py — Write features_config.json for a given scene.

Accepts the list of features to ENABLE as a comma-separated string.
All other features are disabled.  Localization methods and channel-charting
methods are written with sensible defaults for ablation runs (nn_classification
and all charting methods are disabled to keep runs fast).

Usage
-----
    python3 write_features_config.py <scene_name> <enabled_features> [options]

    scene_name        — scene folder name (e.g. Otaniemi_small)
    enabled_features  — comma-separated list of feature group names to enable.
                        Use "ALL" to enable every feature group.
    --methods <list>  — comma-separated localization methods to enable.
                        Default: "wknn,nn_regression,cnn_regression"

Available feature group names
------------------------------
    ofdm_mag_gd, tdoa, aoa, rss, path_loss, delay, cov_eigenvalues, reached_flags

Examples
--------
    # All features on (base cache run)
    python3 write_features_config.py Otaniemi_small ALL

    # Only geometry-related features
    python3 write_features_config.py Otaniemi_small tdoa,aoa,delay

    # All features except OFDM (faster inference, smaller model)
    python3 write_features_config.py Otaniemi_small tdoa,aoa,rss,path_loss,delay,cov_eigenvalues,reached_flags

    # All features, also enable nn_classification
    python3 write_features_config.py Otaniemi_small ALL --methods wknn,nn_regression,nn_classification,cnn_regression
"""

import argparse
import json
import sys
from pathlib import Path

ALL_FEAT_KEYS = [
    "ofdm_mag_gd",
    "tdoa",
    "aoa",
    "rss",
    "path_loss",
    "delay",
    "cov_eigenvalues",
    "reached_flags",
]

ALL_LOC_KEYS = ["wknn", "wknn_c2f", "nn_regression", "nn_classification", "cnn_regression", "ensemble"]
ALL_CC_KEYS  = ["pca", "tsne", "autoencoder", "umap"]


def write_features_config(
    scene_name: str,
    enabled_feats: list[str],
    enabled_methods: list[str] | None = None,
    enable_charting: bool = False,
) -> Path:
    """Write ``<scene_name>/features_config.json`` and return its path.

    Parameters
    ----------
    scene_name      : Scene folder name.
    enabled_feats   : Feature group names to enable (others are disabled).
    enabled_methods : Localization method names to enable.
                      Defaults to wknn + nn_regression + cnn_regression.
    enable_charting : When ``True``, all channel-charting methods are enabled.
                      Default ``False`` (skip charting during ablation runs).

    Returns
    -------
    Path  — path to the written features_config.json.
    """
    if enabled_methods is None:
        enabled_methods = ["wknn", "nn_regression", "cnn_regression"]

    enabled_feat_set   = set(enabled_feats)
    enabled_method_set = set(enabled_methods)

    cfg = {
        "_comment": (
            "Generated by write_features_config.py — edit manually or re-run the script."
        ),
        "fingerprint_features": {
            k: (k in enabled_feat_set) for k in ALL_FEAT_KEYS
        },
        "localization": {
            k: (k in enabled_method_set) for k in ALL_LOC_KEYS
        },
        "channel_charting": {
            k: enable_charting for k in ALL_CC_KEYS
        },
    }

    out_path = Path(scene_name) / "features_config.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as fh:
        json.dump(cfg, fh, indent=2)

    enabled_str  = ", ".join(k for k in ALL_FEAT_KEYS if k in enabled_feat_set) or "none"
    disabled_str = ", ".join(k for k in ALL_FEAT_KEYS if k not in enabled_feat_set) or "none"
    print(f"Wrote {out_path}")
    print(f"  Features ON  : {enabled_str}")
    print(f"  Features OFF : {disabled_str}")
    print(f"  Methods      : {', '.join(k for k in ALL_LOC_KEYS if k in enabled_method_set)}")
    return out_path


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Write features_config.json for ablation testing.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("scene_name",        help="Scene folder name")
    parser.add_argument(
        "enabled_features",
        help='Comma-separated feature names to enable, or "ALL"',
    )
    parser.add_argument(
        "--methods",
        default="wknn,nn_regression,cnn_regression",
        help="Comma-separated localization methods to enable (default: wknn,nn_regression,cnn_regression)",
    )
    parser.add_argument(
        "--charting",
        action="store_true",
        help="Also enable all channel-charting methods",
    )

    args = parser.parse_args(argv)

    feat_arg = args.enabled_features.strip()
    if feat_arg.upper() == "ALL":
        enabled_feats = list(ALL_FEAT_KEYS)
    else:
        enabled_feats = [f.strip() for f in feat_arg.split(",") if f.strip()]
        unknown = set(enabled_feats) - set(ALL_FEAT_KEYS)
        if unknown:
            print(f"ERROR: Unknown feature name(s): {unknown}", file=sys.stderr)
            print(f"Valid names: {ALL_FEAT_KEYS}", file=sys.stderr)
            sys.exit(1)

    enabled_methods = [m.strip() for m in args.methods.split(",") if m.strip()]
    unknown_m = set(enabled_methods) - set(ALL_LOC_KEYS)
    if unknown_m:
        print(f"ERROR: Unknown method name(s): {unknown_m}", file=sys.stderr)
        sys.exit(1)

    write_features_config(
        args.scene_name,
        enabled_feats,
        enabled_methods,
        enable_charting=args.charting,
    )


if __name__ == "__main__":
    main()
